**Preamble**

**Colloboration Policy**. The student is to *explicitly identify* his/her collaborators in the assignment. If the student did not work with anyone, he/she should indicate `Collaborators=['none']`. If the student obtains a solution through research (e.g., on the web), acknowledge the source, but *write up the solution in HIS/HER OWN WORDS*. There will be a one mark penalty if a student fails to indicate his/her collaborators.

**There will be NO EXCEPTIONS to this grading policy.**

# Assignment 2 - Sensitivity Analysis

If you need help on using Jupyter notebooks, click <a href='#help'>here</a>. 

Objective:

In this exercise, we perform *sensity analysis* to a specific linear program (LP). 
That is, we analyse the effect of changing parameters on the optimal solution and optimal value.
Specifically, we will look at the following scenarios:

(a) Change in *objective function* for the coefficient of a *nonbasic* variable.

(b) Change in *objective function* for the coefficient of a *basic* variable.

(c) Change in a *RHS* value.

(d) Adding a new *variable*.

(e) Adding a new *constraint*.



# Linear Program LP1

For this assignment, **LP1** refers to the following linear program:

$$
\begin{array}{crcrcrcrl}
\max &   &   & x_2 & - & x_3 & + & x_4\\ 
\text{subject to} 
& x_1 & - &  x_2 & - & 3x_3 & + &  x_4 & \le 7\\ 
&3x_1 & + &  x_2 & + &  x_3 & + & 2x_4 & \le 2\\ 
&6x_1 & + & 2x_2 & + & 3x_3 & - &  x_4 & \le 1\\ 
\end{array}
$$

Note that when we refer to **LP1**. It refers to above problem with **no other modifications**.

In [1]:
# WE COMPUTE THE SOLUTION FOR LP1 HERE

import pulp

model = pulp.LpProblem("LP1", pulp.LpMaximize)

x1 = pulp.LpVariable('x1', lowBound=0)
x2 = pulp.LpVariable('x2', lowBound=0)
x3 = pulp.LpVariable('x3', lowBound=0)
x4 = pulp.LpVariable('x4', lowBound=0)

model += x2-x3+x4, "Z"


model +=   x1 -   x2 - 3*x3 +   x4  <=  7,           "constraint1"
model += 3*x1 +   x2 +   x3  + 2*x4 <=  2,           "constraint2"
model += 6*x1 + 2*x2 + 3*x3 -   x4  <=  1,           "constraint3"

print(model)

model.solve()

print("Z  : {}".format(pulp.value(model.objective)))

print("x1 : {}".format(x1.varValue))
print("x2 : {}".format(x2.varValue))
print("x3 : {}".format(x3.varValue))
print("x4 : {}".format(x4.varValue))


LP1:
MAXIMIZE
1*x2 + -1*x3 + 1*x4 + 0
SUBJECT TO
constraint1: x1 - x2 - 3 x3 + x4 <= 7

constraint2: 3 x1 + x2 + x3 + 2 x4 <= 2

constraint3: 6 x1 + 2 x2 + 3 x3 - x4 <= 1

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

Z  : 1.4
x1 : 0.0
x2 : 0.8
x3 : 0.0
x4 : 0.6


**(0) (5 marks)** Fill in the entries for the *optimal* simplex table.
Show your working. However, feel free to use `numpy` to do the computations (click <a href='#matrix'>here</a> for simple `numpy` matrix operations).

Do take note of the order of the decision variables.

Introduce slack variable and solve the LP1_slack


In [3]:
# You may need to use python for some computations


import pulp


slackmodel = pulp.LpProblem("LP1_slack", pulp.LpMaximize)

x1 = pulp.LpVariable('x1', lowBound=0)
x2 = pulp.LpVariable('x2', lowBound=0)
x3 = pulp.LpVariable('x3', lowBound=0)
x4 = pulp.LpVariable('x4', lowBound=0)
u1 = pulp.LpVariable('u1', lowBound=0)
u2 = pulp.LpVariable('u2', lowBound=0)
u3 = pulp.LpVariable('u3', lowBound=0)


# object function

slackmodel += x2 -x3 +x4, "Z"

# constraints 
slackmodel +=   x1 -   x2 - 3*x3 +    x4 + u1  ==  7,           "constraint1"
slackmodel += 3*x1 +   x2 +   x3  + 2*x4 + u2  ==  2,           "constraint2"
slackmodel += 6*x1 + 2*x2 + 3*x3 -    x4 + u3  ==  1,           "constraint3"

print(slackmodel)

slackmodel.solve()

print("Maximum: {}".format(pulp.value(slackmodel.objective)))

print("x1: {}".format(x1.varValue))
print("x2: {}".format(x2.varValue))
print("x3: {}".format(x3.varValue))
print("x4: {}".format(x4.varValue))
print("u1: {}".format(u1.varValue))
print("u2: {}".format(u2.varValue))
print("u3: {}".format(u3.varValue))

LP1_slack:
MAXIMIZE
1*x2 + -1*x3 + 1*x4 + 0
SUBJECT TO
constraint1: u1 + x1 - x2 - 3 x3 + x4 = 7

constraint2: u2 + 3 x1 + x2 + x3 + 2 x4 = 2

constraint3: u3 + 6 x1 + 2 x2 + 3 x3 - x4 = 1

VARIABLES
u1 Continuous
u2 Continuous
u3 Continuous
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

Maximum: 1.4
x1: 0.0
x2: 0.8
x3: 0.0
x4: 0.6
u1: 7.2
u2: 0.0
u3: 0.0


The matrix equation is as follow:



| $Z$ | $x_2$ | $x_4$ | $u_1$ | $x_1$ | $x_3$ | $u_2$ | $u_3$ | RHS |
| :-: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |:---:|
| 1   |  -1   |  -1   |   0   |   0   |   1   |   0   |   0   |  0  |
| 0   |  -1   |   1   |   1   |   1   |   -3  |   0   |   0   |  7  |
| 0   |   1   |   2   |   0   |   3   |   1   |   1   |   0   |  2  |
| 0   |   2   |  -1   |   0   |   6   |   3   |   0   |   1   |  1  |

In [2]:
# Using NUMPY for calculations...

import numpy as np 

CB = np.matrix([
    [1,1,0],
])


CN= np.matrix([
    [0,-1,0,0],
])


B = np.matrix([
    [-1,1,1],
    [1,2,0],
    [2,-1,0],
])



N = np.matrix([
    [1,-3,0,0],
    [3,1,1,0],
    [6,3,0,1],
])


b= np.matrix([
    [7],
    [2],
    [1],
])


# to determine inverse(B)N
print("===========================================================================")
print("inverse(B)N=")
invB_N=np.linalg.inv(B)*N
print(invB_N)

# to determine inverse(B)b
print("===========================================================================")
print("inverse(B)b=")
invB_b=np.linalg.inv(B)*b
print(invB_b)


# to determine -(CN - CB * inverse(B)*N)
print("===========================================================================")
print("-CN - CB*inverse(B)*N=")
final_CN =-(CN-CB*(np.linalg.inv(B)*N))
print(final_CN)


# to determine CB*inverse(B)b
print("===========================================================================")
print("CB*inverse(B)*b=")
final_CB =CB*(np.linalg.inv(B)*b)
print(final_CB)

 

inverse(B)N=
[[ 3.00000000e+00  1.40000000e+00  2.00000000e-01  4.00000000e-01]
 [ 1.11022302e-16 -2.00000000e-01  4.00000000e-01 -2.00000000e-01]
 [ 4.00000000e+00 -1.40000000e+00 -2.00000000e-01  6.00000000e-01]]
inverse(B)b=
[[0.8]
 [0.6]
 [7.2]]
-CN - CB*inverse(B)*N=
[[3.  2.2 0.6 0.2]]
CB*inverse(B)*b=
[[1.4]]


---

**Answer - Optimal Simplex Table**. 

| $Z$ | $x_2$ | $x_4$ | $u_1$ | $x_1$ | $x_3$ | $u_2$ | $u_3$ | RHS |
| :-: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |:---:|
| 1   |   0   |   0   |   0   |   3   |   2.2 |   0.6 |   0.2 | 1.4 |
| 0   |   1   |   0   |   0   |   3   |   1.4 |   0.2 |   0.4 | 0.8 |
| 0   |   0   |   1   |   0   |   0   |  -0.2 |   0.4 |  -0.2 | 0.6 |
| 0   |   0   |   0   |   1   |   4   |  -1.4 |  -0.2 |   0.6 | 7.2 |


---

**(a) (2 marks)**  Consider a new objective function 
$$ c_1x_1 +x_2-x_3+x_4.$$

For what values of $c_1$, will the optimal value remain at $1.4$?


In [39]:
CB_invB_N = CB*(np.linalg.inv(B))*N

print("CB*invB*N=")
print(CB_invB_N)

CB*invB*N=
[[3.  1.2 0.6 0.2]]


$-C_N $changes from (0,1,0,0) to  ($-c_1$, 1, 0, 0)

As shown above, 

$ C_B*B^{-1}*N = $ (3,1.2,0.6,0.2)

$ -(C_N - C_B*B^{-1}*N) =  -C_N + C_B*B^{-1}*N  = $ ($3-c_1$, 2.2, 0.6, 0.2) 

Since $3-c_1 \ge 0$, 


Hence, the answer is &nbsp; &nbsp; $c_1 \le 3$

**(b) (2 marks)**  Consider a new objective function 
$$c_2x_2-x_3+x_4.$$

For what values of $c_2$, will the optimal basis remain unchanged?

In [50]:
print("invB*b=")
print(invB_b)
print("==========================================================================")
print("invB*N=")
print(invB_N)
print("==========================================================================")

invB*b=
[[0.8]
 [0.6]
 [7.2]]
invB*N=
[[ 3.00000000e+00  1.40000000e+00  2.00000000e-01  4.00000000e-01]
 [ 1.11022302e-16 -2.00000000e-01  4.00000000e-01 -2.00000000e-01]
 [ 4.00000000e+00 -1.40000000e+00 -2.00000000e-01  6.00000000e-01]]



$ -C_B {\text{changes from}}  (-1,-1,0) {\text{to}}  (-c_2, -1, 0) $

$ -C_N =  (0,1,0,0)  $
***
$
-C_B*B^{-1}*N =
\left(\begin{array}{cc} 
-c_2 & -1 & 0
\end{array}\right)
\left(\begin{array}{cc} 
3 & 1.4 & 0.2 & 0.4\\
0 & -0.2 & 0.4 & -0.2\\
4 & -1.4 & -0.2 & 0.6
\end{array}\right)
=
\left(\begin{array}{cc} 
-3c_2 & -1.4c_2+0.2 & -0.2c_2-0.4 & -0.4c_2+0.2
\end{array}\right)
$
***
$
C_N+(-C_B*B^{-1}*N) =
\left(\begin{array}{cc} 
0 & -1 & 0 & 0
\end{array}\right)
+
\left(\begin{array}{cc} 
-3c_2 & -1.4c_2+0.2 & -0.2c_2-0.4 & -0.4c_2+0.2
\end{array}\right)
=
\left(\begin{array}{cc} 
-3c_2 & -1.4c_2-0.8 & -0.2c_2-0.4 & -0.4c_2+0.2
\end{array}\right)
$

***

Zero constraint 1: &nbsp; $-3c_2 \le 0$   &nbsp; &nbsp;==> &nbsp; &nbsp;     $ c_2 \ge 0 $

Zero constraint 2: &nbsp; $-1.4c_2-0.8 \le 0$ &nbsp; &nbsp;==> &nbsp; &nbsp;     $ c_2 \ge -4/7 $
      
Zero constraint 3: &nbsp; $-0.2c_2-0.4 \le 0$ &nbsp; &nbsp;==> &nbsp; &nbsp;     $ c_2 \ge -2 $

Zero constraint 4: &nbsp; $-0.4c_2+0.2 \le 0$  &nbsp; &nbsp;==> &nbsp; &nbsp;     $ c_2 \ge 1/2 $&nbsp;

Thus, $ c_2 \ge 1/2 $

***

$
C_B*B^{-1}*b =
\left(\begin{array}{cc} 
c_2 & 1 & 0 
\end{array}\right)
\left(\begin{array}{cc} 
0.8\\
0.6\\
7.2
\end{array}\right)
=
\left(\begin{array}{cc} 
0.8c_2+0.6
\end{array}\right)
$


Hence, the answer is when &nbsp; &nbsp; $c_2 \ge 1/2$ , &nbsp; &nbsp;the optimal basis is unchanged.

**(c) (2 marks)**  Suppose we modify `"constraint 1"` to  
$$ x_1 - x_2 - 3x_3 + x_4 \le b_1.$$

For what values of $b_1$, will the optimal basis remain unchanged?

In [49]:
print("invB=")
invB = np.linalg.inv(B)
print(invB)
print("==========================================================================")

invB=
[[ 0.   0.2  0.4]
 [ 0.   0.4 -0.2]
 [ 1.  -0.2  0.6]]


 b  changes from (7,2,1) to  ($b_1$, 2, 1) 

***
$
B^{-1}*b =
\left(\begin{array}{cc} 
0 & 0.2 & 0.4\\
0 & 0.4 & -0.2\\
1 & -0.2 & 0.6
\end{array}\right)
\left(\begin{array}{cc} 
b_1 \\
2 \\
1 
\end{array}\right)
=
\left(\begin{array}{cc} 
0.8\\
0.6\\
b+0.2
\end{array}\right)
$
***
Zero constraint : &nbsp; $b +0.2 \ge 0$   


Thus,  $ b_1 \ge -0.2 $



$
C_B*B^{-1}*b =
\left(\begin{array}{cc} 
1 & 1 & 0 
\end{array}\right)
\left(\begin{array}{cc} 
0.8\\
0.6\\
b_1+0.2
\end{array}\right)
=
\left(\begin{array}{cc} 
1.4
\end{array}\right)
$


When &nbsp; &nbsp; $b_1\ge -0.2$ , &nbsp; &nbsp;the optimal basis is unchanged.

**(d) (2 marks)** Suppose we add a new variable to **LP1** and the new linear program is:

$$
\begin{array}{crcrcrcrcrl}
\max &   &   & x_2 & - & x_3 & + & x_4 & + &c_5x_5\\ 
\text{subject to} 
& x_1 & - &  x_2 & - & 3x_3 & + &  x_4 & + & x_5 & \le 7\\ 
&3x_1 & + &  x_2 & + &  x_3 & + & 2x_4 & + & x_5 & \le 2\\ 
&6x_1 & + & 2x_2 & + & 3x_3 & - &  x_4 & + & x_5 & \le 1\\ 
\end{array}
$$
For what values of $c_5$, will the optimal value remain unchanged?


In [56]:
NEW_N = np.matrix([
    [1,-3,0,0,1],
    [3,1,1,0,1],
    [6,3,0,1,1],
])

final = -(CB * invB * NEW_N)
print("-CB_inv(B)_N=")
print(final)

-CB_inv(B)_N=
[[-3.  -1.2 -0.6 -0.2 -0.8]]


By adding a new  variable x5, the N changes to

$
N =
\left(\begin{array}{cc} 
1 & -3 & 0 & 0 & 1\\
3 & 1 & 1 & 0 & 1\\
6 & 3 & 0 & 1 & 1
\end{array}\right)
$


$
-C_N =
\left(\begin{array}{cc} 
0 & 1 & 0 & 0 & -c_5
\end{array}\right)
$

***
$
-C_B*B^{-1}*N =
\left(\begin{array}{cc} 
-1 & -1 & 0
\end{array}\right)
\left(\begin{array}{cc} 
0 & 0.2 & 0.4\\
0 & 0.4 & -0.2\\
1 & -0.2 & 0.6
\end{array}\right)
\left(\begin{array}{cc} 
1 & -3 & 0 & 0 & 1\\
3 & 1 & 1 & 0 & 1\\
6 & 3 & 0 & 1 & 1
\end{array}\right)
=
\left(\begin{array}{cc} 
-3 & -1.2 & -0.6 & -0.2 & -0.8
\end{array}\right)
$
***
$
C_N+(-C_B*B^{-1}*N) =
\left(\begin{array}{cc} 
0 & -1 & 0 & 0 & c_5
\end{array}\right)
+
\left(\begin{array}{cc} 
-3 & -1.2 & -0.6 & -0.2 & -0.8
\end{array}\right)
=
\left(\begin{array}{cc} 
-3 & -2.2 & -0.6 & -0.2 & c_5-0.8
\end{array}\right)
$

***

Zero constraint : &nbsp; $c_5 -0.8 \le 0$   

Thus, $ c_5 \le 0.8 $

***


Hence, the answer is when &nbsp; &nbsp; $c_5 \le 0.8 $ , &nbsp; &nbsp;the optimal basis is unchanged and the optimal value reamins 1.4.

**(e) (2 marks)** Suppose we add a new constraint to **LP1** and the new constraint is:

$$
x_1+x_2+x_3+x_4\le b_4
$$
For what values of $b_4$, will the optimal solution remain unchanged?

The new matrix with the added new constraint is 

| $Z$ | $x_2$ | $x_4$ |  $u_1$ | $u_4$ | $x_1$ | $x_3$ | $u_2$ | $u_3$ | RHS |
| :-: | :---: | :---: |  :---: | :---: | :---: | :---: | :---: | :---: |:---:|
| 1   |  -1   |  -1   |    0   |   0   |   0   |   1   |   0   |   0   |  0  |
| 0   |  -1   |   1   |    1   |   0   |   1   |  -3   |   0   |   0   |  7  |
| 0   |   1   |   2   |    0   |   0   |   3   |   1   |   1   |   0   |  2  |
| 0   |   2   |  -1   |    0   |   0   |   6   |   3   |   0   |   1   |  1  |
| 0   |   1   |   0   |    0   |   1   |   1   |   1   |   0   |   0   |  b4 |

In [7]:
B = np.matrix([
    [-1,1,1,0],
    [1,2,0,0],
    [2,-1,0,0],
    [1,1,0,1],
])



# to determine inverse(B)N
print("===========================================================================")
print("new inverse(B)")
invB=np.linalg.inv(B)
print(invB)

new inverse(B)
[[ 0.   0.2  0.4  0. ]
 [ 0.   0.4 -0.2  0. ]
 [ 1.  -0.2  0.6  0. ]
 [ 0.  -0.6 -0.2  1. ]]


$
b =
\left(\begin{array}{cc} 
7\\
2\\
1\\
b_4
\end{array}\right)
$

$
C_B =
\left(\begin{array}{cc} 
1 & 1 & 0 & 0
\end{array}\right)
$

$
B^{-1} =
\left(\begin{array}{cc} 
0 & 0.2 & 0.4 & 0\\
0 & 0.4 & -0.2 & 0\\
1 & -0.2 & 0.6 & 0\\
0 & -0.6 & -0.2 & 1
\end{array}\right)
$




$
B^{-1}*b =
\left(\begin{array}{cc} 
0 & 0.2 & 0.4 & 0\\
0 & 0.4 & -0.2 & 0\\
1 & -0.2 & 0.6 & 0\\
0 & -0.6 & -0.2 & 1
\end{array}\right)
\left(\begin{array}{cc} 
7\\
2\\
1\\
b_4
\end{array}\right)
=
\left(\begin{array}{cc} 
0.8\\
0.6\\
7.2\\
b_4-1.4
\end{array}\right)
$


 $b_4 -1.4 \ge 0$   &nbsp; &nbsp;==> &nbsp; &nbsp;     $ b_4 \ge 1.4 $
 
 
 


$
Z=C_B*B^{-1}*b =
\left(\begin{array}{cc} 
1 & 1 & 0 & 0
\end{array}\right)
\left(\begin{array}{cc} 
0.8\\
0.6\\
7.2\\
b_4-1.4
\end{array}\right)
=
\left(\begin{array}{cc} 
1.4
\end{array}\right)
$



Thus, when $ b_4 \ge 1.4 $ , the optimal solution remains 1.4.


---

### Appendix

---

### Using `numpy` for matrix operations

<a id='matrix'></a>


Suppose we want to compute $$U^{-1}V$$
where
$$ 
U =\left(
\begin{array}{ccc}
1 & -6 & 0\\
0 & 2 & 1\\
0 & 2 & 0\\
\end{array}
\right)
\quad
V =\left(
\begin{array}{ccc}
1  &  3 &  0\\
16 & -3 &  0\\
11 & -1 & -1\\
\end{array}
\right)\,.
$$

The syntax is as follows.

In [3]:
import numpy as np # REMEMBER TO INCLUDE THIS LINE!

U = np.matrix([
    [1,-6,0],
    [0, 2,1],
    [0, 2,0],
]
)

V = np.matrix([
    [ 0, 3, 0],
    [16,-3, 0],
    [11,-1,-1],
]
)

M = np.linalg.inv(U)*V
print(M)

[[ 33.    0.   -3. ]
 [  5.5  -0.5  -0.5]
 [  5.   -2.    1. ]]


---

<a id='help'></a>
**Using iPython Notebooks**. When you click to the left of this box, you will notice that this box is highlighted by a slighly larger box. This is a *cell*. 

There are three types of cells in a notebook.

1. Markdown.
2. Code.
3. Raw.

You can change the type of cell by going to *Cell* on the tool bar.

You can *evaluate* cells by hitting **Shift+Enter**. Depending on the type of cells, you will have different outputs.

---

This is a **markdown** cell. Markdown is a lightweight markup language is similar to *html* with significantly less functionalities. However, the syntax is much simpler. You can find a [Markdown Cheatsheet here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

---

In [1]:
# This is a CODE cell.
# After you hit Shift+Enter, it evaluates the cell in Python.
# Take note that in Python, to comment lines, you use the symbol #

print("Hello World!")

Hello World!


**Answering Questions**. You may choose to use *raw* or *markdown* cells to answer the questions. Of course, if the answer requires you to run a routine in Python, please use a *code* cell.
